### ISSUE TITLE
Strange input format error in problem 1008.

### ISSUE THREAD

**Issue by hzcheney** [youngyangyang04/kamacoder-solutions#64]
Hi! I have submitted my answer for problem 1009. Here is the code:
```java
import java.util.*;

public class Main{

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        while (sc.hasNextLine()) {
            int num = sc.nextInt();
            int sum = 0;
            while (num > 0) {
                int a = num % 10;
                if (a % 2 == 0) sum += a;  
                num /= 10;
            }
            System.out.println(sum);
            System.out.println();
        }
    }
}
```
However, it shows the input error as follows:
```
Exception in thread "main" java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at Main.main(Main.java:9)
/1008/test0.in:	    non-zero return = 1 

----time_space_table:----
/1008/sample.in:AC mem=13024k time=148ms
/1008/test0.in:RE mem=13464k time=195ms
```
And the explanation is `non-zero return : Main函数不能返回非零的值，否则视同程序出错。` Should I ignore this and try to use `nextInt()` inside, or is this input format not allowed in kamacoder?

**Comment by charon2121** [comment]
在你的代码中，你使用sc.hasNextLine()来检查是否还有下一行的输入，然后又使用了sc.nextInt()读取下一行的整数。
这就会出现一个问题，当最后一行仅仅是一个回车时，sc.hasNextLine()会返回true，这将会进入循环体，但是此时最后一行并没有整数可供程序读取，所以代码中读取整数的操作就会出现异常。
解决方案是将 while (sc.hasNextLine()) 修改为 while(sc.hasNextInt())；

**Comment by hzcheney** [comment]
Thanks!
